package dev.pikaia.android.sdk.auth.data.devices

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Request to complete device linking.
 *
 * @param token Link token extracted from the QR code deep link
 * @param deviceUuid Stable unique device identifier generated by the app
 * @param name Device name (e.g. "Pixel 9 Pro")
 * @param platform Platform identifier (e.g. "android")
 * @param osVersion Operating system version (e.g. "15")
 * @param appVersion App version (e.g. "1.0.0")
 */
@Serializable
data class CompleteLinkRequest(
    val token: String,
    @SerialName("device_uuid")
    val deviceUuid: String,
    val name: String,
    val platform: String,
    @SerialName("os_version")
    val osVersion: String = "",
    @SerialName("app_version")
    val appVersion: String = ""
)
